export enum MathOperation {
  ADDITION = 'ADDITION',
  SUBTRACTION = 'SUBTRACTION',
  MULTIPLICATION = 'MULTIPLICATION',
  DIVISION = 'DIVISION'
}

export type Language = 'zh-TW' | 'en';

export interface Problem {
  id: string;
  operation: MathOperation;
  operandA: number;
  operandB: number;
  result: number;
  storyContext?: string; // Generated by Gemini
  primaryEmoji?: string;
  secondaryEmoji?: string;
}

export interface DailyTask {
  id: string;
  title: string;
  description: string;
  titleKey?: string;
  descriptionKey?: string;
  target: number;
  current: number;
  completed: boolean;
  reward: number;
  icon: string;
}

export interface UserProfile {
  id?: string; // Firebase uses string IDs
  name: string;
  birthday: string; // YYYYMMDD
  grade: string; // P1-P6
  school: string;
  avatar: string; // Base64 string
}

export interface UserState {
  coins: number;
  streak: number;
  xp: number;
  level: number;
  avatarId: string; // Keep for backward compatibility or defaults
  profile?: UserProfile; // The actual DB profile
  dailyTasks: DailyTask[];
}

export enum AppView {
  LOADING = 'LOADING',
  REGISTRATION = 'REGISTRATION',
  DASHBOARD = 'DASHBOARD',
  GAME = 'GAME',
  REWARDS = 'REWARDS',
  SETTINGS = 'SETTINGS',
  RANKING = 'RANKING'
}